### ISSUE TITLE
你的信誉值已经负1024分了    

### ISSUE THREAD

**Issue by rekols** [deepins/qq-music#1]
@1377195627   你的信誉值已经负1024分了

**Comment by 1377195627** [comment]
@rekols 我说了，不要过度依赖dtk，dtk是好，但还没有完全成熟，别过度依赖是对的。qt原生的东西都没学好就直接用dtk，虽然原生的有些东西用着不爽。但什么都用dtk有屁用，有些东西他就是没有，还不是要自己造组件，有些东西，还不是要写样式表，而且别忘了dlight主题并不完整

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by rekols** [comment]
呵呵，用一个DImageButton就说依赖DTK？一个QPushButton加几段QSS不就完事了么？

**Comment by 1377195627** [comment]
@rekols首先， dimagebutton我并没有用过，第二，还是要写样式表，第三，我用我熟悉的东西写有错？第四，你有哪次不提dtk的组件的，第五，有些东西，本来就是用最快的方式来写，只为效果。第六，首发总是有好的，以后有的是时间重写。第七，我很忙，我不可能只写这么一个，重点的项目都没写完

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by rekols** [comment]
你说dtk精确ｑｔ版本？为什么我ｕｂｕｎｔｕ下qt5.9还可以编译？

**Comment by rekols** [comment]
重点不是提不提dtk

**Comment by 1377195627** [comment]
@rekols 废话，也不看看肥猫给dtk打了多少关于5.9兼容的补丁，arch上的qt就是最新版，dtk不兼容能用？而且arch上几乎所有dde的东西都是肥猫打包维护。而且dtk对qt版本号很敏感这句话是肥猫本人说的。而且你真的以为dtk在qt5.9的环境下就真的一点问题都没有？只是你没发现而已。而且有个跨越好几个月的问题，还是最近才修复了没多久

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by rekols** [comment]
不ＢＢ了，你厉害，我输了．

**Comment by rekols** [comment]
吵这些没用，各写各的代码吧．

**Comment by 1377195627** [comment]
你遇到的坑，还少的很，别以为就这么点屁事

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by rekols** [comment]
好好好，我知道了，我输了

**Comment by 1377195627** [comment]
有些东西，你确实比我会，有些东西，你却不如我，方向不同，好好碰碰底层把

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by 1377195627** [comment]
底层的东西的坑，往往更多，就比如go.dbus，就国内这个环境，谷歌出来的还不是一个样，还不是得自己研究，自己研究出来的用法用的时间，呵，比谷歌还短

_使用 [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github) 从我的 Nubia NX563J 发送_

**Comment by rekols** [comment]
恩恩，好好写代码
